/*
 * generated by Xtext 2.41.0
 */
package com.github.phoswald.sample.mydsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
