/*
 * generated by Xtext 2.41.0
 */
package com.github.phoswald.sample.mydsl.ide;


/**
 * Use this class to register ide components.
 */
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
